version: '3.4'

services:
    feeddb:
        image: postgres

    pgadmin:
        image: dpage/pgadmin4

    feed:
        image: ${DOCKER_REGISTRY-}feed
        build:
            context: .
            dockerfile: Services/FeedService/Feed/Dockerfile

volumes:
    postgres_data:
    pgadmin_data: